version: '2'

services:
  packet-forwarder:
    build: ./hm-pktfwd
    depends_on:
      - helium-miner
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
    environment:
      - FIRMWARE_VERSION=v1.0.0-alpha.21

  helium-miner:
    build: ./hm-gatewayrs
    privileged: true
    expose:
      - "1680"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: on-failure
    environment:
      - RELEASE_BUMPER=foobar
      - FIRMWARE_VERSION=v1.0.0-alpha.21
    labels:
      io.balena.features.balena-api: '1'
  browser:
    image: bhcr.io/balenablocks/browser-aarch64
    privileged: true
    network_mode: host
    ports:
      - '5011'
      - '35173'
    volumes:
      - 'settings:/data'
  audio:
    image: balenablocks/audio
    privileged: true
    ports:
      - '4317:4317'
    environment:
      AUDIO_OUTPUT: RPI_HDMI0

volumes:
  settings: {}
  miner-storage:
  miner-log:
  pktfwdr:
